spring:
  application:
    name: monitoring-demo-app

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: monitoring-demo-app
